export const PRIORITIES = {
  EASY: {
    label: 'Easy',
    xp: 25,
    color: '#10b981',
    textColor: 'text-emerald-400',
    bgClass: 'priority-easy',
    icon: '⚡',
  },
  MEDIUM: {
    label: 'Medium',
    xp: 50,
    color: '#f59e0b',
    textColor: 'text-amber-400',
    bgClass: 'priority-medium',
    icon: '🔥',
  },
  HARD: {
    label: 'Hard',
    xp: 100,
    color: '#f43f5e',
    textColor: 'text-rose-400',
    bgClass: 'priority-hard',
    icon: '💀',
  },
  EPIC: {
    label: 'Epic',
    xp: 200,
    color: '#8b5cf6',
    textColor: 'text-violet-400',
    bgClass: 'priority-epic',
    icon: '👑',
  },
};

export const CATEGORIES = ['Work', 'Personal', 'Health', 'Learning', 'Creative', 'Other'];

export const LEVELS = [
  { level: 1,  title: 'Novice',         minXP: 0,    maxXP: 300,  color: '#94a3b8' },
  { level: 2,  title: 'Apprentice',     minXP: 300,  maxXP: 700,  color: '#34d399' },
  { level: 3,  title: 'Journeyman',     minXP: 700,  maxXP: 1200, color: '#22d3ee' },
  { level: 4,  title: 'Adept',          minXP: 1200, maxXP: 1800, color: '#60a5fa' },
  { level: 5,  title: 'Expert',         minXP: 1800, maxXP: 2600, color: '#a78bfa' },
  { level: 6,  title: 'Veteran',        minXP: 2600, maxXP: 3500, color: '#f472b6' },
  { level: 7,  title: 'Master',         minXP: 3500, maxXP: 4600, color: '#fb923c' },
  { level: 8,  title: 'Grandmaster',    minXP: 4600, maxXP: 6000, color: '#fbbf24' },
  { level: 9,  title: 'Legend',         minXP: 6000, maxXP: 8000, color: '#f59e0b' },
  { level: 10, title: '⚡ Ascendant',  minXP: 8000, maxXP: 8000, color: '#ff6b35' },
];

export const BADGES = [
  {
    id: 'first_quest',
    name: 'First Quest',
    description: 'Complete your very first task',
    icon: '⚔️',
    color: '#34d399',
    condition: (stats) => stats.totalCompleted >= 1,
    rarity: 'Common',
  },
  {
    id: 'hat_trick',
    name: 'Hat Trick',
    description: 'Complete 3 tasks',
    icon: '🎯',
    color: '#22d3ee',
    condition: (stats) => stats.totalCompleted >= 3,
    rarity: 'Common',
  },
  {
    id: 'ten_tasks',
    name: 'Task Master',
    description: 'Complete 10 tasks',
    icon: '📋',
    color: '#60a5fa',
    condition: (stats) => stats.totalCompleted >= 10,
    rarity: 'Uncommon',
  },
  {
    id: 'twenty_five_tasks',
    name: 'Quest Veteran',
    description: 'Complete 25 tasks',
    icon: '🏆',
    color: '#f59e0b',
    condition: (stats) => stats.totalCompleted >= 25,
    rarity: 'Rare',
  },
  {
    id: 'streak_3',
    name: 'On Fire',
    description: 'Maintain a 3-day streak',
    icon: '🔥',
    color: '#fb923c',
    condition: (stats) => stats.streak >= 3,
    rarity: 'Common',
  },
  {
    id: 'streak_7',
    name: 'Week Warrior',
    description: 'Maintain a 7-day streak',
    icon: '🌟',
    color: '#fbbf24',
    condition: (stats) => stats.streak >= 7,
    rarity: 'Uncommon',
  },
  {
    id: 'streak_30',
    name: 'Legendary Grind',
    description: 'Maintain a 30-day streak',
    icon: '⚡',
    color: '#8b5cf6',
    condition: (stats) => stats.streak >= 30,
    rarity: 'Legendary',
  },
  {
    id: 'level_5',
    name: 'Expert Rank',
    description: 'Reach Level 5',
    icon: '💎',
    color: '#a78bfa',
    condition: (stats) => stats.level >= 5,
    rarity: 'Rare',
  },
  {
    id: 'level_10',
    name: 'Ascendant',
    description: 'Reach the maximum level',
    icon: '👑',
    color: '#ff6b35',
    condition: (stats) => stats.level >= 10,
    rarity: 'Legendary',
  },
  {
    id: 'epic_slayer',
    name: 'Epic Slayer',
    description: 'Complete 5 Epic difficulty tasks',
    icon: '🐉',
    color: '#8b5cf6',
    condition: (stats) => stats.epicCompleted >= 5,
    rarity: 'Rare',
  },
  {
    id: 'early_bird',
    name: 'Early Bird',
    description: 'Complete a task before 9 AM',
    icon: '🌅',
    color: '#fbbf24',
    condition: (stats) => stats.earlyBird === true,
    rarity: 'Uncommon',
  },
  {
    id: 'speed_runner',
    name: 'Speed Runner',
    description: 'Complete 5 tasks in a single day',
    icon: '⚡',
    color: '#22d3ee',
    condition: (stats) => stats.maxTasksInDay >= 5,
    rarity: 'Rare',
  },
];

export const TASKS_PER_PAGE = 8;

export const RARITY_COLORS = {
  Common: '#94a3b8',
  Uncommon: '#34d399',
  Rare: '#60a5fa',
  Legendary: '#f59e0b',
};
